import type { Career } from '@/types';

export const mockCareers: Career[] = [
  {
    id: '1',
    title: 'Frontend Developer',
    description: 'Build modern web interfaces with React, TypeScript, and Next.js',
    salary: { min: 95000, max: 155000 },
    growth: 'Much faster than average',
    growth_rate: '22%',
    education: "Bachelor's degree",
    experience: '2-4 years',
    skills: ['React', 'TypeScript', 'CSS', 'HTML', 'Next.js'],
    tasks: ['Build UI components', 'Optimize performance', 'Write tests', 'Code reviews'],
    match: 94,
    cluster: 'Software Engineering',
  },
  {
    id: '2',
    title: 'Machine Learning Engineer',
    description: 'Design and deploy ML models for production systems',
    salary: { min: 130000, max: 185000 },
    growth: 'Much faster than average',
    growth_rate: '35%',
    education: "Master's degree",
    experience: '3-5 years',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'SQL', 'MLOps'],
    tasks: ['Train models', 'Feature engineering', 'Model deployment', 'A/B testing'],
    match: 89,
    cluster: 'AI / Machine Learning',
  },
  {
    id: '3',
    title: 'Full Stack Engineer',
    description: 'Build end-to-end web applications from database to UI',
    salary: { min: 110000, max: 170000 },
    growth: 'Faster than average',
    growth_rate: '18%',
    education: "Bachelor's degree",
    experience: '3-5 years',
    skills: ['Node.js', 'React', 'PostgreSQL', 'Docker', 'AWS'],
    tasks: ['API development', 'Database design', 'Frontend builds', 'DevOps'],
    match: 87,
    cluster: 'Software Engineering',
  },
  {
    id: '4',
    title: 'Data Scientist',
    description: 'Extract insights from complex datasets using statistical methods',
    salary: { min: 105000, max: 165000 },
    growth: 'Much faster than average',
    growth_rate: '28%',
    education: "Master's degree",
    experience: '2-4 years',
    skills: ['Python', 'R', 'SQL', 'Statistics', 'Visualization'],
    tasks: ['Data analysis', 'Model building', 'Reporting', 'Experimentation'],
    match: 82,
    cluster: 'Data Science',
  },
  {
    id: '5',
    title: 'DevOps Engineer',
    description: 'Automate infrastructure and streamline deployment pipelines',
    salary: { min: 115000, max: 175000 },
    growth: 'Faster than average',
    growth_rate: '20%',
    education: "Bachelor's degree",
    experience: '3-5 years',
    skills: ['Kubernetes', 'Docker', 'Terraform', 'CI/CD', 'AWS'],
    tasks: ['Pipeline automation', 'Monitoring', 'Infrastructure as code', 'Incident response'],
    match: 76,
    cluster: 'Infrastructure',
  },
  {
    id: '6',
    title: 'Product Manager',
    description: 'Define product strategy and drive cross-functional execution',
    salary: { min: 120000, max: 180000 },
    growth: 'Average',
    growth_rate: '15%',
    education: "Bachelor's degree",
    experience: '4-6 years',
    skills: ['Strategy', 'Analytics', 'User Research', 'Agile', 'SQL'],
    tasks: ['Roadmap planning', 'Stakeholder management', 'Sprint planning', 'User interviews'],
    match: 71,
    cluster: 'Product',
  },
];
